### PR TITLE
SOED9-136: Work for the responsive views of the spotlights page.

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW

# Summary
- Fixes the image size 
- Fixes the responsive views
-- Cards go full width and stack at the LG breakpoint 
- Updated SCSS to use more of the Decanter mixins
-- Fonts
-- Responsive spacing 
- Filter stacks when in responsive view
- Reviewed spacing/fonts with Design teammate

# Review By (Date)
- ASAP

# Criticality
- High

# Urgency
- High

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to /spotlight
4. Verify the cards all stack at the large breakpoint.
5. Verify the spotlight top banner stacks at large breakpoint.
5. Verify the See more Spotlights is linked correctly.
6. Navigate to spotlight node page
4. Verify the see more cards at bottom all stack at the large breakpoint.
5. Verify the spotlight top banner stacks at large breakpoint.

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory? YES

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/SOED9-136

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by mdyoung3** [comment]
Loaded it on my local. Looks good so far.

**Review by mdyoung3 — APPROVED** [review]
Looks good.

**Comment by jenbreese** [comment]
@mdyoung3 There is a codeception test failing. Can you take a look at why?

**Comment by mdyoung3** [comment]
@jenbreese Maybe Ian ran it again. Its current status is passed.

**Review by imonroe — APPROVED** [review]

**Pull request merged**
