### PR TITLE
SOED9-110 - rebranched from lastest changes to avoid merge conflcts.

### PR DESCRIPTION
**Pull request by mdyoung3**
#11  READY FOR REVIEW

# Summary
- The Stanford pages migration.

# Review By (Date)
- ASAP

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Urgency
- High

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Open the composer.json file and replace `dev-8.x-2.x` with `dev-SOED9-110`.
3. Run `composer update su-soe/engineering_profile`
4. Import config files. Should only be four of them. 
5. Run `drush cim -y`
6. Run `drush ms` to check for any errors. If errors appear, then try rebuilding the cache and run it again. If errors persist, let me know.
7. Finally run ` drush migrate:import --group=stanford_pages_d7` 
8. Open the site and got to /admin/content, and check for the new content. Which should mirror the XML file. https://engineering.stanford.edu/export/stanford-pages
9. Open as many pages as would give confidence that the body and titles came over correctly. 

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory? 
   Yes.

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/SOED9-110

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by mdyoung3** [comment]
@imonroe I ran imports on this, and the paths worked for me. This looks good as well.

**Comment by mdyoung3** [comment]
@imonroe I think this should be good for merge. Let me know what you think. Thanks.

**Comment by imonroe** [comment]
Are we not worrying about images on these?

**Comment by mdyoung3** [comment]
We can talk about this in more depth today at stand up. 

One thing to consider is, there are about 83 nodes with images. It could take a dev a day or two to update the XML feed, update the yaml migrate files,  review PRs, etc... Whereas a Sal might be able to copy and paste these over in the same amount of time.

**Pull request merged**
