### PR TITLE
SOED9-77: Magazine configs

### PR DESCRIPTION
**Pull request by imonroe**
# READY FOR REVIEW

# Summary
- This PR has the configs necessary for the additional fields and functionality for magazine stories on the engineering site.
- additionally, there are updates I've pulled in from the `soe_profile` which bring us up to date with that as well.

# Needed By (Date)
- asap

# Urgency
- medium

# Steps to Test

1. Check out this branch.
2. `drush cim` (it may need a `blt drupal:update` instead, since there's a bunch of changes)
3. Try to create a new News item; notice the addition of the new fields for SOE and for the magazine specifically.
4. verify nothing breaks.

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by imonroe** [comment]
Sorry for the mess of commits; I've been fiddling with this for some time, and I wanted to make sure it was right.

**Comment by mdyoung3** [comment]
Hi Ian,

Importing the new files results in a missing module error:

``` [error]  Drupal\Core\Config\ConfigImporterException: There were errors validating the config synchronization.
Unable to install the <em class="placeholder">pdb</em> module since it does not exist. in Drupal\Core\Config\ConfigImporter->validate() (line 748 of /var/www/docroot/core/lib/Drupal/Core/Config/ConfigImporter.php).```

I tried your suggestion of running `blt drupal:update`. The error persisted. So I then ran `composer install` to no avail. 

Best,
Marc

**Comment by imonroe** [comment]
> Hi Ian,
> 
> Importing the new files results in a missing module error:
> 
> ```
> Unable to install the <em class="placeholder">pdb</em> module since it does not exist. in Drupal\Core\Config\ConfigImporter->validate() (line 748 of /var/www/docroot/core/lib/Drupal/Core/Config/ConfigImporter.php).
> ```
> 
> I tried your suggestion of running `blt drupal:update`. The error persisted. So I then ran `composer install` to no avail.
> 

Ah, right.  I pulled in the changed from soe_profile, which included the `pdb` module which was just installed the other day.  Try switching the dependency in your root composer.json to:
```
"su-soe/engineering_profile": "dev-SOED9-77-magazine-configs"
```
and then do a `composer update`.  that should do the trick.

**Review by mdyoung3 — APPROVED** [review]
After tweaking the composer.json files--per Ian and my slack convo--with a few changes, I was able to see the new fields. 

Screen Shot 2021-07-01 at 3 17 09 PM

**Pull request merged**
