### PR TITLE
July 2022 release

### PR DESCRIPTION
**Pull request by imonroe**
# READY FOR REVIEW

# Summary
- engineering profile 8.5.3 release for July 2022.

# Review By (Date)
- ASAP

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Urgency
- How urgent is this? (Normal, High)

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to...
4. Verify...

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory?

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by mdyoung3** [comment]
Holy deprecated function, batman! 

I see from a conversation on Slack this is resolved by turning it off in the settings file.

**Comment by imonroe** [comment]
> Holy deprecated function, batman!
> 
> I see from a conversation on Slack this is resolved by turning it off in the settings file.

Yeah, that's correct.  I included that in the stack repo for acquia environments and a toggle for localdev so I could continue to test against it locally.

**Comment by mdyoung3** [comment]
That's good thinking. I like that much better than adding to the settings.php

**Comment by mdyoung3** [comment]
Ian,

I'm sometimes seeing this error:

Screen Shot 2022-08-02 at 11 34 12 AM
 
Sometimes via Drush and sometimes in admin UI.

I see it was an issue in D7: https://stanfordwebservices.slack.com/archives/G0A50QC49/p1580424080072200?thread_ts=1580417323.066400&cid=G0A50QC49

**Comment by imonroe** [comment]
> @imonroe ,
> 
> I'm sometimes seeing this error:
> 
> Screen Shot 2022-08-02 at 11 34 12 AM
> 
> Sometimes via Drush and sometimes in admin UI.
> 
> I see it was an issue in D7: [stanfordwebservices.slack.com/archives/G0A50QC49/p1580424080072200?thread_ts=1580417323.066400&cid=G0A50QC49](https://stanfordwebservices.slack.com/archives/G0A50QC49/p1580424080072200?thread_ts=1580417323.066400&cid=G0A50QC49)

That is an issue with the encrypted values for the stanford_person importer.

To correct it:

Get the correct encryption salt value from the server via drush

drush @default.prod eval 'echo getenv("STANFORD_ENCRYPT");'

Put that value into your local.settings.php file:

putenv('STANFORD_ENCRYPT=XXXXXXXXXXXXXXX');

**Comment by mdyoung3** [comment]
@imonroe 

That fixed it! Thanks.

Looking good after all the things (cache rebuild, update database, cron, etc...):

Screen Shot 2022-08-02 at 1 05 27 PM

After the tests pass, I think we're good to go on this.

**Comment by mdyoung3** [comment]
You know what. I'm not that worried about test. I'll go ahead and give my stamp of approval. 

LGTM

**Review by mdyoung3 — APPROVED** [review]

**Pull request closed without merging**
